### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by ai** [borodean/postcss-assets#16]
What is a changes in 2.0.0? I think every project must have `ChangeLog.md` so users willunderstand what is changed, when they see I new version on npm.

**Comment by borodean** [comment]
@ai But it has [a change log here already?](https://github.com/borodean/postcss-assets/releases)

**Comment by ai** [comment]
Ouh, I missed it (most of projects don’t use GitHub releases). Very nice.

**Comment by ai** [comment]
@borodean Do not forget to update GitHub Releases for 2.1.0 release (separated `ChangeLog` file is better in this case, because you will not forget to update it. It’s update must be part of release commit)

**Comment by borodean** [comment]
@ai I did it instantly https://github.com/borodean/postcss-assets/releases :-)
