### ISSUE TITLE
Use PostCSS 4.1 API

### ISSUE THREAD

**Issue by TrySound** [borodean/postcss-assets#20]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by borodean** [comment]
Points that postcss-assets is not currently following are:
- create plugin via `postcss.plugin`;
- test against io.js;
- `postcss-plugin` keyword in `package.json`;
- use asynchronous methods when it is possible.

Am I missing something?

**Comment by TrySound** [comment]
Test on node 12 or io.js need if you want to use promise API. In your case it should be async, so yes.
And do not use `fs.exists` or `fs.existsSync` methods, caz it's deprecated.

For now make at least postcss.plugin and postcss-plugin keyword.

**Comment by ai** [comment]
I think 2 step migration is a best way:

1. Fixing keyword, `postcss.plugin`, adding `io.js` to Travis CI.
2. Migrate to async methods.

**Comment by borodean** [comment]
Good plan, @ai.

>Fixing keyword, postcss.plugin, adding io.js to Travis CI.

This is now implemented in [2.1.2](https://github.com/borodean/postcss-assets/releases/tag/2.1.2).

**Comment by TrySound** [comment]
@borodean  Minor release please.

**Comment by borodean** [comment]
@TrySound why minor? I've added no functionality.

**Comment by ai** [comment]
BTW, `[major].[minor].[patch]`, so `minor` is a for public API extending.

**Comment by borodean** [comment]
@ai I don't think any public API changed in 2.1.2, only the way its made. Am I wrong?

**Comment by ai** [comment]
@borodean `patch` is for no API changes. You are right.
