### ISSUE TITLE
Realtive/Base path confusion

### ISSUE THREAD

**Issue by mikestreety** [borodean/postcss-assets#22]
Hello,

This isn't so much as an "issue", but not sure where else to put it. I was struggling a bit with using the `resolve()` function with Gulp and Sass and such.

My folder structure is:

```
gulpfile.js

public_html/
  assets/
    project/
      css/
      img/

build/
  project/
    css/
    img/
```

The scss and images are in the build folder. The `project` folder is client specific. Sometimes we have one CMS install for several sites, so there will be a folder parallel to `project` folder with a different name but with CSS and JS in. Becuase of this, I can't hardcode the `project` folder in the gulpfile.

Gulp currently watches the CSS folder for sass changes and compiles it to `public_html/assets` with the same path. The same is for the images, where they get optimised on their journey over.

I couldn't seem to get the `postcss-assets` to make a path of `/assets/<path>`. I could get it to have `public_html` in the path but not take this off.

My sass is like this:

```
div {
    background: resolve('../img/bg.png');
}
```

This then gets compiled with the full path, but back to `build` (which is outside the `public_html` - so the image can't be rendered).

My current way of solving this is to compile the scss, put the file in the `public_html` folder and then `postcss` that - which seems a bit odd.

Any ideas? Happy to be a guinea pig. I did try every which way I could with all the different settings but couldn't work it out. 

I would like to use the `resolve` function for the cachebusting.

**Comment by borodean** [comment]
Hi @mikestreety! Could you please explain more on folders parallel to the `project` one: give a real-world example and point out where their contents are getting compiled?

**Comment by mikestreety** [comment]
Hi @borodean - thanks for getting back to me.

Due to the nature of the set up, I can't provide actual real-world examples, but will produce a scenario.

Say we have a client called Steve. Steve has two companies - Steve's Boats and Steve's Jetskis. Although the two sites are completely unrelated, Steve manages both sites. To save on resources, server space and login faff, we have one CMS that manages both sites. All Steve has to do, is log in to one CMS and he can hop between the sites to update his prices.

The CMS then accesses the `assets` folder, and pulls out the CSS and Images related to that one site. Because there are the same client & "site", we have one `gulp` task for both websites.

The build folder would look something like this:

```
build/
    boats/
        css/
        img/
    
    jetskis/
        css/
        img/
```

These files then compile to the `assets` folder in the `public_html` folder - this means the site root only has compiled assets.

The folder structure is completely replicated:

```
public_html/
    assets/
        boats/
            css/
            img/
        
        jektskis/
            css/
            img/
```

Does this make it any clearer?

**Comment by borodean** [comment]
@mikestreety, I've replicated your structure and tried this:

```js
var gulp = require('gulp');

gulp.task('copy', function () {
  return gulp.src('build/**/img/**/*.*')
    .pipe(gulp.dest('public_html'));
});

gulp.task('css', function () {
  var postcss = require('gulp-postcss');

  return gulp.src('build/**/*.css')
    .pipe(postcss([
      require('postcss-assets')({
        basePath: 'build'
      })
    ]))
    .pipe(gulp.dest('public_html'));
});

gulp.task('default', ['copy', 'css']);
```

The `basePath` option sets which directory to treat as the website root path. Since the children structures under `build` and `public_html` directories are the same this works fine for both.

The URLs I got inside resulting CSS look like this:

```css
.boats {
  background: url('/assets/boats/img/boat.jpg');
} 
```

Does it works for you?

**Comment by borodean** [comment]
No answer for a month, closing the issue. @mikestreety, if there anything else I can help here, feel free to post in this thread.

**Comment by mikestreety** [comment]
@borodean I'm so sorry - I completely read this but forgot to reply. I will have a look and a test and get back to you. Sorry and thank you :smile:

**Comment by borodean** [comment]
@mikestreety no worries! :-) Thanks and looking forward for a reply.

**Comment by mikestreety** [comment]
I've just had a chance to have a play and replicate the above. In your example, it works fine except it doesn't put it in an `assets` folder. When I try to get it to do this, the compiled URL is still omitting the `assets` part of the path.

Sorry to put this on you - I appreciate it's an edge case, which I'm not expecting you to bend over backwards for!

**Comment by borodean** [comment]
@mikestreety hmm, but that one is still fine on my machine. I've sent you an email with my whole setup attached, please check it out and let me know how it works.

**Comment by mikestreety** [comment]
Thanks @borodean - I'll have a look at get back to you

**Comment by borodean** [comment]
@mikestreety any news? :-)

**Comment by makingoff** [comment]
#39 @borodean look at this please. It may solve this issue
