### ISSUE TITLE
Wrong size of svg

### ISSUE THREAD

**Issue by jonnitto** [borodean/postcss-assets#33]
If I have a svg with a viewbox (e.g "0 0 130 19") the result of size() ist not "130px 19px". It is "100px 100px", because of the attributes width="100%" height="100%".

**Comment by borodean** [comment]
@jonnitto that's an issue with [image-size](https://github.com/netroy/image-size). I'd submit a pull request fixing it, but the project looks abandonded. I'm going to migrate postcss-assets to [calipers](https://github.com/lob/calipers). It doesn't have SVG support yet, but is actively developed so I'm going to contribute them.

**Comment by borodean** [comment]
@jonnitto so I wouldn't expect a fix for this until calipers supports SVG.

**Comment by borodean** [comment]
@jonnitto finally, the new version of `image-size` resolving this issue got released! Should be fixed in Assets 3.0.3, could you verify it works for you?
