### ISSUE TITLE
Usage with postcss-at2x

### ISSUE THREAD

**Issue by 7rulnik** [borodean/postcss-assets#34]
Hi! I use postcss-assets. It's really cool, thank you.

Can I use it with [postcss-at2x](https://github.com/simonsmith/postcss-at2x)?

This way don't work:
```
background: inline('./img/image.png') at-2x;
```

**Comment by borodean** [comment]
@7rulnik postcss-at2x expects `url` function to be found inside background declaration. Put postcss-assets before postcss-at2x in the list of processors, so the later gets `inline` and `resolve` functions compiled to `url`:

```js
gulp.src('style.css')
  .pipe([
    require('postcss-assets'),
    require('postcss-at2x') // at2x goes after assets
  ])
  // ...
```
