### ISSUE TITLE
Can’t find repo

### ISSUE THREAD

**Issue by ashleynolan** [borodean/postcss-assets#37]
I’m having some issues when using an old version of postcss-assets (v2.1.3).

Started getting the following error on npm install:

```
npm ERR! Error: Command failed: Cloning into bare repository '/Users/ashley.nolan/.npm/_git-remotes/git-github-com-borodean-image-size-0541338d'...
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/borodean/image-size/' not found
```

Is this something that can be fixed?  Looks like it’s looking for a fork that no longer exists? (we can’t upgrade to the latest version right now as we’re in process of upgrading our build servers to something that ressembles recent!)

Thanks

**Comment by duncanhall** [comment]
Also seeing this, seems like it breaks any version prior to the latest.

**Comment by borodean** [comment]
@ashleynolan @duncanhall sorry for that, I've revived the private fork. However, I'm going to remove it again somewhere this winter when a new release of PostCSS Assets is released — I don't want backwards compatibility to throttle plugin's development.

Also, I should add a note to the README about the versions that could be affected by it.

**Comment by borodean** [comment]
Okay, I guess I can re-publish older versions of a library with fixed dependencies. Will do that later, for now it should be fine with the revived fork.

**Comment by borodean** [comment]
@ashleynolan @duncanhall I've published a patched 2.1.x under version 2.1.4 where the private fork is no longer used.

In conclusion, releases 2.1.0—3.0.2 would no longer work without that private fork existing. But now for the 3.0.x versions there is 3.0.3 fixing this thing, and for 2.1.x there is 2.1.4 doing so.

Since there are solutions for every minor version now, I'll remove the fork again.

Sorry for the inconvenience and thanks for reporting.

**Comment by ashleynolan** [comment]
@borodean thanks for the fix – all working as expected now :+1:

**Comment by hudochenkov** [comment]
@borodean this republish bring new issue: `npm install postcss-assets` installs 2.1.4 instead of 3.0.3 and PostCSS 5 is very unhappy with this :)

**Comment by borodean** [comment]
@hudochenkov crappy crap. That happened because I've published 2.1.4 after 3.0.3.

Hmm, I wonder how this could be fixed.

**Comment by hudochenkov** [comment]
@borodean maybe publish 3.0.3 again, or bump to 3.0.4 and publish.

**Comment by borodean** [comment]
This command fixed the issue:
```bash
npm dist-tag add postcss-assets@3.0.3 latest
```
Thanks for reporting, @hudochenkov!

**Comment by hudochenkov** [comment]
@borodean thank you for quick fixing :)
