### ISSUE TITLE
Ability to delete assets after inlining.

### ISSUE THREAD

**Issue by DylanPiercey** [borodean/postcss-assets#48]
This feature could be useful for builds where images are also optimized and copied into a bin folder. This way there wouldn't have to be a public facing copy of the image and the dist folder can be smaller.

**Comment by borodean** [comment]
@DylanPiercey please share your ideas on how this could work. If the plugin would just delete the inlined files, it would fail to inline them again on the next compilation.

**Comment by DylanPiercey** [comment]
In my proposed scenario the files would have been built/optimized by a tool an would be rebuilt before each css build.

**Comment by mabar** [comment]
Images should be optimized only when changed. And manipulating so much with filesystem in CSS sounds like a side effect. Just delete them yourself after compilation if it is required.

**Comment by DylanPiercey** [comment]
@mabar fair enough. I'm using web pack for this now anyways :).
