### ISSUE TITLE
Common PostCSS API

### ISSUE THREAD

**Issue by ai** [borodean/postcss-assets#6]
Most of PostCSS plugins works as `plugin` instead of `plugin()` if there is no options.

```js
postcss([
    require('autoprefixer-core'),
    require('postcss-nested'),
    require('postcss-mixins'),
    require('postcss-assets')() // ugly
])
```

I make this behavior by:

```js
module.exports = function (opts) {
    //  work with options
    return function (css) {
        // work with AST
    };
};

module.exports.postcss = function (css) {
    module.exports()(css);
};
```

**Comment by borodean** [comment]
@ai if this would be implemented, and since it changes the API, how `semver` says the version should be updated?

**Comment by ai** [comment]
I think here is `x.x.X` release, because it is expected behaviour and we fix it.

But also we you change `x.X.x`, because we add new API (but didn’t broke old APIs).
