### ISSUE TITLE
Using pkg.name in basePath / loadPaths

### ISSUE THREAD

**Issue by stevygee** [borodean/postcss-assets#69]
I often use `<%= pkg.name %>` in my Gruntfile to refer to the project directory in paths.

I just came across a situation where I wanted to do the same in postcss-assets' options. Specifically, I have a config variable `slug` set in my package.json and want to use it like this:

```
    postcss: {
      options: {
          map: false,
          processors: [
              require('postcss-assets')({
                basePath: 'build/<%= pkg.config.slug %>',
                loadPaths: ['images/'],
                relative: true,
                cachebuster: false
              })
          ]
      },
      style: {
          src: 'build/<%= pkg.config.slug %>/style.css'
      }
    },
```

With this I get a file not found or unreadable error.
It works fine when I hardcode the directory name in basePath.

**Comment by borodean** [comment]
https://github.com/borodean/postcss-assets/issues/66
