### ISSUE TITLE
Not working in PostCSS 6.0.1

### ISSUE THREAD

**Issue by vforge** [borodean/postcss-assets#70]
Here's the error/warning message after updating to PostCSS 6.0.1

`Your current PostCSS version is 6.0.1, but postcss-functions uses 5.2.17`.

**Comment by borodean** [comment]
@vforge this is not the issue of the postcss-assets itself. However, I've made a PR for postcss-functions to fix this: https://github.com/andyjansson/postcss-functions/pull/20

**Comment by borodean** [comment]
@vforge merged and released in `postcss-assets@5.0.0`.

**Comment by vforge** [comment]
Oh, great! I'll test later. Thanks for the poke.
