### ISSUE TITLE
Protocol agnostic URL getting wrongly added.

### ISSUE THREAD

**Issue by popkutty** [borodean/postcss-assets#75]
I have a style like the before

`load{
background: url("//www.example.com/example.gif") no-repeat;
}` 

this is getting created after build

`load{
background: url("//example.com/example.gif") no-repeat;
}` 

which is failing in my case to download the assets.

**Comment by borodean** [comment]
@popkutty I don't see how it's related to `postcss-assets`. The plugin deals with the `resolve()`, `inline()`, `width()`, `height()` and `size()` pseudofunctions, but has nothing to do with the vanilla `url()` one.

Why do you think it is related?

**Comment by borodean** [comment]
Close due to inactivity.
