### ISSUE TITLE
How to use postcss-assets in npm script

### ISSUE THREAD

**Issue by cristian05** [borodean/postcss-assets#76]
Hi, i have a question. 
How can I use the plugion assets in npm script?, and how can I set its options?

Something like this?

"scripts": {
      "assets": "postcss -u postcss-assets --relative ./public --base-path ./public --load-path ['/fonts'] -r 
      ./public/css/style.css"
}

**Comment by borodean** [comment]
@cristian05 you have to create a postcss.config.js file: https://github.com/postcss/postcss-cli#config
