### ISSUE TITLE
What happened to the cachebuster?

### ISSUE THREAD

**Issue by depoulo** [borodean/postcss-assets#81]
It looks like it got removed with 934e2e764b263a101738ee7dc6543065059a30be, meaning that 3.0.3 is the last release containing it. But the [two](https://github.com/borodean/postcss-assets/commit/0375617ed7adc7d8b10e4c637777d7008b119022) most [recent](https://github.com/borodean/postcss-assets/commit/845639345fbf4f489f9024451192c168defa1083) commits update the cachebuster documentation so what's going on here?

**Comment by borodean** [comment]
@depoulo all of that kind of functionality was extracted to https://github.com/borodean/assets.

For instance, here is the cachebuster thing: https://github.com/borodean/assets/blob/develop/lib/url.js#L45
